### ISSUE TITLE
Erro ao criar conta

### ISSUE THREAD

**Issue by Echenique** [lucasgiovannibr/canaryaac#4]
Segui o tutorial que esta no gitbook, o site esta rodando, porem ao tentar criar uma account, após preencher os formulários e enviar, me deparo com o seguinte erro:

"Connection could not be established with host "localhost:25": stream_socket_client(): Unable to connect to localhost:25 (Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente)"

Alguem pode me ajudar?

**Comment by lucasgiovannibr** [comment]
Error fixed, please update and try again.
