### ISSUE TITLE
PHP Error - Creating Character

### ISSUE THREAD

**Issue by Peixonauta2** [lucasgiovannibr/canaryaac#5]
Hello
I've found some errors and I really don't know if that occurs only if using xampp:

Issue: After you create your account, if you try to create a character and for some reason, you forget to select a sex or vocation, a error will be displayed:

```
Warning: Undefined array key "sex" in C:\xampp\htdocs\app\Controller\Pages\Account\CreateCharacter.php on line 79
Warning: Undefined variable $converted in C:\xampp\htdocs\app\Model\Functions\Player.php on line 389
```

![image](https://user-images.githubusercontent.com/63183357/195196047-9803f961-fc2e-4b90-b520-839edd30b78f.png)

The problem seems to happen aswell if trying to create an account and no selecting a sex for the first character:

```
Warning: Undefined variable $converted in C:\xampp\htdocs\app\Model\Functions\Player.php on line 389
```

![image](https://user-images.githubusercontent.com/63183357/195197256-8c216541-100b-44fa-aa71-d5d1de57204b.png)

Since I'm no PHP expert, I've tried to find some solutions and a if condition to verify if the the fields are empty seemed to solve the problem:

**CreateCharacter.php**
```       
if(empty($postVars['sex'])){
            return self::viewCreateCharacter($request, 'Set a sex for the character.');
        }
        if(empty($postVars['vocation'])){
            return self::viewCreateCharacter($request, 'Set a vocation for the character.');
        }
```

**Comment by lucasgiovannibr** [comment]
Thanks for reporting.
Fixed bug and added a few more things.
