### ISSUE TITLE
Outfits Images/Cache are not working

### ISSUE THREAD

**Issue by montycode** [lucasgiovannibr/canaryaac#8]
### **Description:**
Hey there! Hope everything it's going good, I've installed the CanarayAAC and all is working like a charm but the Outfits images. I don't know if I have to call something else/extra to force the server to add all the outfits/looktypes to the /cache folder, but currently I can't see any outfit been working. Visiting the image source url shows: **_Outfit does not exist or file cache is not generated._**

### **Screen Shots:**
![image](https://user-images.githubusercontent.com/43155049/206884062-61b8010e-5bb5-4c32-8830-29faf78a2138.png)
![image](https://user-images.githubusercontent.com/43155049/206884070-e6b37caf-3f12-4d02-bf48-f8a346d8610c.png)
![image](https://user-images.githubusercontent.com/43155049/206884080-27e949ca-4850-46bd-9d09-25d88dfe6e51.png)

Thanks in advance for your help!
I'm using the last release from the main branch.

**Comment by Imperio1992** [comment]
Hello Mi config is in Config.php:

// images
	'outfit_images_url' => 'https://outfit-images.ots.me/1285_walk_animation/animoutfit.php', // set to animoutfit.php for animated outfit https://outfit-images.ots.me/outfit.php  
	'item_images_url' => 'http://apocalipsce-rl.ddns.net/images/items', // set to images/items if you host your own items in images folder https://item-images.ots.me/1285_otservbr/



youw use link of page: ---> 'https://outfit-images.ots.me/

**Comment by SRNT-GG** [comment]
I would strongly advise against relying on a remote host like that, unless you operate it why would you rely on a resource that could go offline the next second?

**Comment by libergod** [comment]
Hi!!

Please check: 

60e6882c607e4d11f9dc863783939926ccd19f24
